### ISSUE TITLE
ModuleNotFoundError: No module named 'supar.config'

### ISSUE THREAD

**Issue by Thomas-Maged** [CAMeL-Lab/camel_parser#3]
when running this command to pass the input: "python text_to_conll_cli.py -f text -i input.txt"
this error appears: "ModuleNotFoundError: No module named 'supar.config'"
![camel parser1](https://github.com/CAMeL-Lab/camel_parser/assets/133599574/7f4200a3-5641-4af7-9a79-09ea1450deb1)
![image](https://github.com/CAMeL-Lab/camel_parser/assets/133599574/af6cd657-ef79-4006-9f57-c5673b53f288)

**Comment by muhammed-abuodeh** [comment]
Which python version are you using? CamelParser currently works with 3.9.16, and I haven't tested it with a later version.

**Comment by muhammed-abuodeh** [comment]
The README was improved in order to deal with this error, and the code was tested and is working. If you face another problem, please submit another issue.
