### ISSUE TITLE
Parsing with UD model yields CATiB trees

### ISSUE THREAD

**Issue by mirkovogel** [CAMeL-Lab/camel_parser#4]
The parser creates CATiB trees regardless of the `--model` parameter, whereas the `--tags` parameter works as expected. Given the Idafa construct   "بيت الأميرة", the link should be `NMOD : POSS` when using the UD model, but it's always `IDF`.

```
> camel_parser$ python3 text_to_conll_cli.py -t catib6 -m catib  -f text -s "بيت الأميرة"
# text = بيت الأميرة
# treeTokens = بيت الأميرة
1	بيت	بيت	NOM	_	ud=NOUN|pos=noun|prc3=0|prc2=0|prc1=0|prc0=0|enc0=0|asp=na|vox=na|mod=na|gen=m|num=s|stt=c|cas=n|per=na|rat=i|token_type=baseword	0	---	__
2	الأميرة	أمير	NOM	_	ud=NOUN|pos=noun|prc3=0|prc2=0|prc1=0|prc0=Al_det|enc0=0|asp=na|vox=na|mod=na|gen=f|num=s|stt=d|cas=g|per=na|rat=r|token_type=baseword	1	IDF	__

> camel_parser$ python3 text_to_conll_cli.py -t ud -m ud  -f text -s "بيت الأميرة"
# text = بيت الأميرة
# treeTokens = بيت الأميرة
1	بيت	بيت	NOUN	_	catib6=NOM|pos=noun|prc3=0|prc2=0|prc1=0|prc0=0|enc0=0|asp=na|vox=na|mod=na|gen=m|num=s|stt=c|cas=n|per=na|rat=i|token_type=baseword	0	---	__
2	الأميرة	أمير	NOUN	_	catib6=NOM|pos=noun|prc3=0|prc2=0|prc1=0|prc0=Al_det|enc0=0|asp=na|vox=na|mod=na|gen=f|num=s|stt=d|cas=g|per=na|rat=r|token_type=baseword	1	IDF	_	_

```

I get the same result when I load the model directly from python, so I'm fairly sure that the UD model is actually used:
```python
ud_parser = Parser.load(root_dir/"models/CAMeLBERT-UD-biaffine.model")
```

A quick sanity check shows that the file sizes of the UD and the CATiB models are different and that the checksum matches the model file on hf datasets (https://huggingface.co/CAMeL-Lab/camelbert-ud-parser/blob/main/CAMeLBERT-UD-biaffine.model)

```
> camel_parser/models$ ls -lL
-rw-rw-r-- 1 mirko mirko 445288869 Feb 14 11:10 CAMeLBERT-CATiB-biaffine.model
-rw-rw-r-- 1 mirko mirko 445287236 Feb 14 11:10 CAMeLBERT-UD-biaffine.model

> camel_parser/models$ sha256sum CAMeLBERT-UD-biaffine.model
a7d95213e52dac93f1ddbc395b710e16f6f7e15dcf20f2b2987ea0b84dd6d575  CAMeLBERT-UD-biaffine.model
```

**Comment by muhammed-abuodeh** [comment]
This error was fixed in a previous commit, you can use the following:
python text_to_conll_cli.py  -m ud  -f text -s "بيت الأميرة"

We removed the parameter that asks to pass a tagset; the model you choose will dictate the tagset.
