### ISSUE TITLE
Missing supar.config Module Causes ModuleNotFoundError   

### ISSUE THREAD

**Issue by SrinathReddy123** [CAMeL-Lab/camel_parser#5]
upon running the command: python text_to_conll_cli.py -f text -s "جامعة نيويورك أبو ظبي تنشر أول أطلس لكوكب المريخ باللغة العرب

I'm encountering a ModuleNotFoundError when attempting to load a parser model using the supar package. It seems that the config.py file, which was previously part of the supar package, has been removed in recent updates. This is causing issues with my existing codebase that relies on the supar.config module for loading models.

<img width="956" alt="github issue" src="https://github.com/user-attachments/assets/8310d2ef-bc8a-4419-abde-f403cb4f542f">

**Comment by kathrein** [comment]
I do the same and got the same error, how to fix it?

**Comment by muhammed-abuodeh** [comment]
Which python version are you using? Currently, CamelParser was tested using python 3.9.16, I still haven't tested it with later versions of python.

Can you try with this version and let me know how it goes?

**Comment by kathrein** [comment]
Hi
Yes, it is still the same problem,
I tried again, new one environment and python 3.9.16
Firstly, it said no module supar, I pip install it and then the same error
No module named supar.config.
I think it is updated version of supar that they removed the config which makes the error on camel parser, I also checked the github repo, many people reported the same issue!!
Best
Chatrine

Sent from Outlook for iOS<https://aka.ms/o0ukef>

Chatrine Qwaider
Postdoctoral Associate I
T: N/A
E: ***@***.***
www.mbzuai.ac.ae<https://mbzuai.ac.ae/>

Mohamed bin Zayed University of Artificial Intelligence
Masdar City, Building 1B, 3rd Floor
Abu Dhabi, UAE

[cid:32_5f0d4623-c70a-4f6f-aa82-dcb8eb00c458.png]
 The world’s first specialized research-based AI university

[cid:bannerforjan2024_aaa8fcd0-fd35-4740-a28c-f68e7694b572.gif]
<https://mbzuai.ac.ae/sustainability/>


________________________________

**Comment by muhammed-abuodeh** [comment]
Yes that is why we selected a specific version of supar in the requirements.txt . So when you install using  ` pip install -r requirements.txt ` you should install a version that doesn't give this error. Have you done so?

**Comment by kathrein** [comment]
I did, pip install -r requirements.txt
But when I run camel parser examples as mentioned in git repo,
It generates the error.
May be the old version of supar is not working
Best
Chatrine

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by muhammed-abuodeh** [comment]
The README was improved and the code was tested and is working. If you have any other issues, please submit another issue.
